language: rust
matrix:
 include:
   - rust: nightly
     env: FEATURES="--features unstable"
   - rust: beta
   - rust: stable
   - rust: nightly

script: cd test-project && cargo test $FEATURES

notifications:
  email:
    - pmunksgaard@gmail.com
    - laumann.thomas@gmail.com
