language: rust
rust:
 - stable
 - nightly
matrix:
 include:
   - rust: stable
     env: FEATURES="--features stable"
   - rust: nightly
     env: FEATURES=""

install: cargo build --verbose $FEATURES
script: cd test-project && cargo test $FEATURES

notifications:
  email:
    - pmunksgaard@gmail.com
    - laumann.thomas@gmail.com
