language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES=""
    - rust: beta
      env: FEATURES="--features stable"
    - rust: stable
      env: FEATURES="--features stable"
    - rust: nightly
      env: FEATURES="--features stable"

script: cd test-project && cargo test $FEATURES

notifications:
  email:
    - pmunksgaard@gmail.com
    - laumann.thomas@gmail.com
