environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - if %CHANNEL%==stable (cargo build --features stable) else (cargo build)
  - cd test-project && if %CHANNEL%==stable (cargo test --features stable) else (cargo test)

branches:
  only:
    - master
